

apiVersion: v1
kind: ServiceAccount
metadata:
  name: # Modify this line with the service name
---
apiVersion: v1
kind: Service
metadata:
  name: # Modify this line with the service name
  labels:
    app: # Modify this line with the service name
    service: # Modify this line with the service name
spec:
  ports:
  - port: # Modify this line with the listening port
    name: http
  selector:
    app: # Modify this line with the service name
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: # Modify this line with the service name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: # Modify this line with the service name
  template:
    metadata:
      labels:
        app: # Modify this line with the service name
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: # Modify this line with the service name
      containers:
      - name: # Modify this line with the service name
        image: nicholasjackson/fake-service:v0.24.2
        imagePullPolicy: IfNotPresent
        env:
          - name: NAME
            value: "" # Modify this line with the service name
          - name: LISTEN_ADDR
            value: "0.0.0.0:" # Modify this line with the service name
          - name: MESSAGE
            value: "" # Modify this line with the service name
          - name: UPSTREAM_URIS
            value: "" # Modify this line with target service+portnum
